export const CV_URL =
  'https://res.cloudinary.com/dkrutkbjs/raw/upload/v1/portfolio/Ayodele_Ayoola_CV.pdf';

export const personal = {
  name: "Ayodele Ayoola",
  short: "AYOOLA",
  initials: "AO",
  title: "Software Developer",
  location: "London, United Kingdom",
  email: "ayodeleayoolaoke4@gmail.com",
  phone: "+447551113208",
  linkedin: "linkedin.com/in/ayodele-ayoola",
  summary:
    "Software Developer with 6+ years of experience building scalable products across PropTech, FinTech, and Web3. I specialise in React, Next.js, Flutter and TypeScript, with strong full-stack capability across Node.js, MongoDB, and cloud infrastructure. I’ve led the development of investor platforms, AI-powered systems, and high-scale applications serving millions of users. I focus on performance, system design, and turning complex data into intuitive user experiences.",
};

export const projects = [
  // ===== FEATURED =====
  {
    num: "01",
    title: "PAA - Property Analysis Assistant",
    desc: "AI-powered property intelligence platform with mapping, yield calculations, comparables, and planning insights. Built data-heavy UI, map-based querying, and investor workflows.",
    tags: ["Next.js", "TypeScript", "Maps", "AI", "Web3", "PostGIS", "Tailwind"],
    year: "2026",
    href: "https://paa.scansanproperties.com",
    featured: true,
    company: "ScanSan Properties",
    logo: "SS",
    logoUrl: "https://static.wixstatic.com/media/d1ac02_fb90f30d1cc445efbee8efb1e79bd24e%7Emv2.png",
    logoColor: "#1a3a1a",
  },
  {
    num: "02",
    title: "ScanSan Browser Extension",
    desc: "Property intelligence extension overlaying insights directly on listing platforms.",
    tags: ["React", "TypeScript", "Browser Extension"],
    year: "2026",
    href: "https://chromewebstore.google.com/detail/makigdomcnfjklokllmkachmemmbepfo?utm_source=item-share-cb",
    featured: true,
    company: "ScanSan Properties",
    logo: "SE",
    logoUrl: "https://static.wixstatic.com/media/d1ac02_fb90f30d1cc445efbee8efb1e79bd24e%7Emv2.png",
    logoColor: "#1a3a1a",
  },
  {
    num: "03",
    title: "RentSpace Platform",
    desc: "Full PropTech + FinTech ecosystem with savings, payments, and property workflows.",
    tags: ["Next.js", "Flutter", "Node.js", "MongoDB", "ExpressJs", "Paystack", "WatuPay", "FSB-regulated payments infrastructure", "GCP"],
    year: "2025",
    href: "https://rentspace.tech",
    featured: true,
    company: "RentSpace Technologies",
    logo: "RT",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/rentspace_logo_emqkro.png",
    logoColor: "#1a1a3a",
  },
  {
    num: "04",
    title: "SwiftVista (Utility Payment System)",
    desc: "Utility payments platform for airtime, data, bills, and subscriptions.",
    tags: ["Node.js", "MongoDB", "Flutter", "ExpressJs", "React", "Tailwind"],
    year: "2025",
    href: "https://swiftwave.vercel.app/",
    featured: true,
    company: "Swift Vista",
    logo: "SW",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031796/Swiftvista.7ce5aee9_ia2mdr.png",
    logoColor: "#0f172a",
  },
  {
    num: "05",
    title: "Food Delivery Platform",
    desc: "Full-stack ordering and delivery system built for the Nigerian diaspora in London.",
    tags: ["React", "Node.js", "Stripe", "ExpressJs", "MongoDB", "Tailwind"],
    year: "2026",
    href: "#",
    featured: true,
    company: "Dammy's Kitchen",
    logo: "FD",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031913/logo-Cjjg64Ai_ezz7ug.png",
    logoColor: "#7c2d12",
  },
  {
    num: "06",
    title: "Vanguard Media Platform",
    desc: "High-scale news platform serving millions of users monthly.",
    tags: ["React", "Node.js", "Flutter", "Redis", "WordPress", "Tailwind", "PHP"],
    year: "2023",
    href: "https://vanguardngr.com",
    featured: true,
    company: "Vanguard Media",
    logo: "VM",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/vanguardlogo_egkk3q.png",
    logoColor: "#3a1a1a",
  },

  // ===== ADDITIONAL REAL PROJECTS =====
  {
    num: "07",
    title: "Rentspace Mobile App",
    desc: "Cross-platform savings and lending mobile application with rewards system and payments integration.",
    tags: ["Flutter", "Node.js", "MongoDB"],
    year: "2025",
    href: "",
    featured: true,
    company: "RentSpace",
    logo: "RT",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/rentspace_logo_emqkro.png",
    logoColor: "#1a1a3a",
  },
  {
    num: "08",
    title: "Vanguard Mobile App",
    desc: "News application enabling users to read and save articles with high performance and scalability.",
    tags: ["Flutter", "REST API"],
    year: "2023",
    href: "",
    featured: true,
    company: "Vanguard Media",
    logo: "VM",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/vanguardlogo_egkk3q.png",
    logoColor: "#3a1a1a",
  },
  {
    num: "09",
    title: "Zummit Africa Platform",
    desc: "AI learning and marketplace platform for developers and AI tools.",
    tags: ["React", "Typescript", "MUI"],
    year: "2022",
    href: "https://zummitafrica.com",
    featured: true,
    company: "Zummit Africa",
    logo: "ZA",
    logoUrl: "https://zummitafrica.com/meta/apple-touch-icon.png",
    logoColor: "#1a2a2a",
  },
  {
    num: "10",
    title: "Dowell Research Platform (UX Living Labs)",
    desc: "Enterprise UX research platform with global payment integrations.",
    tags: ["React", "Django", "Stripe", "Paypal", "Styled Components"],
    year: "2022",
    href: "https://dowellresearch.uk",
    featured: true,
    company: "Dowell Research",
    logo: "DR",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/dowell_logo_a61jso.jpg",
    logoColor: "#2a1a2a",
  },
  {
    num: "11",
    title: "Dales E-commerce",
    desc: "Frontend e-commerce platform with checkout, cart, and tracking features.",
    tags: ["React", "Tailwind"],
    year: "2021",
    href: "https://dales-shop.vercel.app/",
    featured: true,
    company: "Personal Project",
    logo: "Dales",
    logoUrl: "",
    logoColor: "#1f2937",
  },
  {
    num: "12",
    title: "Nowon Security",
    desc: "Security services platform with custom backend and responsive frontend.",
    tags: ["Django", "Bootstrap"],
    year: "2021",
    href: "https://now-on.vercel.app/",
    featured: true,
    company: "Nowon",
    logo: "NS",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777032441/now_on_third_new_logo2026_kzlois.jpg",
    logoColor: "#111827",
  },
  {
    num: "13",
    title: "Savannah Living",
    desc: "Accessibility-focused platform for users with learning disabilities.",
    tags: ["Django", "JavaScript"],
    year: "2020",
    href: "https://ssll.pythonanywhere.com/",
    featured: true,
    company: "Savannah Living",
    logo: "SL",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777032610/savannah_logo_o6achi.jpg",
    logoColor: "#374151",
  },
  {
    num: "14",
    title: "Soundz Music App",
    desc: "Music streaming app with Spotify and YouTube integrations.",
    tags: ["Flutter", "Dart"],
    year: "2021",
    href: "https://github.com/CreedTech/soundz",
    featured: true,
    company: "Personal Project",
    logo: "SM",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777032693/ic_launcher_u5ttpv.png",
    logoColor: "#111827",
  },
  {
    num: "15",
    title: "Nurika Health App",
    desc: "Fitness and crypto rewards app combining wellness with incentives.",
    tags: ["Flutter", "Dart"],
    year: "2024",
    href: "https://github.com/CreedTech/nurika_mobile",
    featured: true,
    company: "Nurika",
    logo: "NH",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777032829/splash_logo_fxrqet.png",
    logoColor: "#065f46",
  },
  {
    num: "16",
    title: "Krypt Web3 App",
    desc: "Web3 demo application for sending crypto and displaying transaction feedback.",
    tags: ["React", "Solidity"],
    year: "2022",
    href: "https://web-3-test-project.vercel.app/",
    featured: true,
    company: "Personal Project",
    logo: "KW",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777032902/logo_2_xnbwkw.png",
    logoColor: "#1e3a8a",
  },
];
export const experience = [
  {
    role: "Senior Frontend Engineer",
    company: "ScanSan Properties",
    location: "London, UK",
    period: "June 2025 – Present",
    stack: ["Next.js", "TypeScript", "Tailwind", "Maps", "Web3", "AI"],
    desc:
      "Leading frontend development for a Web3-powered property investment platform. Built the Property Analysis Assistant (PAA), delivering complex data visualisation tools including yield analysis, comparables, planning insights, and geospatial intelligence. Contributed to white-labelling architecture, browser extension tooling, internal dashboards, onboarding flows, and performance optimisation across map-heavy interfaces.",
    logo: "SS",
    logoUrl:
      "https://static.wixstatic.com/media/d1ac02_fb90f30d1cc445efbee8efb1e79bd24e%7Emv2.png",
    logoColor: "#1a3a1a",
    domain: "scansanproperties.com",
  },
  {
    role: "Software Developer",
    company: "RentSpace Technologies",
    location: "London, UK",
    period: "Aug 2023 – May 2025",
    stack: ["Flutter", "Next.js", "Node.js", "MongoDB", "Paystack", "Flutterwave"],
    desc:
      "Rebuilt and scaled a PropTech + FinTech platform across web, mobile, backend, admin dashboard, and public website. Delivered the RentSpace mobile app, implemented secure backend authentication, payment flows, savings features, rewards mechanics, and analytics dashboards. Supported thousands of users and contributed to engineering hiring, onboarding, and technical direction.",
    logo: "RT",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/rentspace_logo_emqkro.png",
    logoColor: "#1a1a3a",
    domain: "rentspace.tech",
  },
  {
    role: "Senior Full-Stack Developer",
    company: "Vanguard Media Limited",
    location: "Remote",
    period: "Apr 2022 – Aug 2023",
    stack: ["React", "Node.js", "Flutter", "REST API", "Redis", "WordPress"],
    desc:
      "Built and optimised high-traffic web and mobile applications for one of Nigeria’s largest media platforms. Worked across frontend, backend, and mobile surfaces, improving performance, cross-platform compatibility, maintainability, and user engagement. Contributed to mobile app experiences, news delivery flows, and scalable integrations with existing content systems.",
    logo: "VM",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/vanguardlogo_egkk3q.png",
    logoColor: "#3a1a1a",
    domain: "vanguardngr.com",
  },
  {
    role: "Software Developer",
    company: "Dowell Research UK",
    location: "London, UK",
    period: "Nov 2021 – Mar 2022",
    stack: ["React", "Python", "Django", "AWS", "Stripe", "PayPal"],
    desc:
      "Developed frontend systems, internal tools, plugins, and research product interfaces for enterprise-focused UX research workflows. Built responsive interfaces, supported reusable package development, integrated payment systems, and collaborated through code reviews to improve maintainability and delivery quality.",
    logo: "DR",
    logoUrl:
      "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/dowell_logo_a61jso.jpg",
    logoColor: "#2a1a2a",
    domain: "dowellresearch.uk",
  },
  {
    role: "React Native Developer",
    company: "FUDAP CO",
    location: "Remote",
    period: "Jan 2021 – Oct 2021",
    stack: ["React Native", "REST API", "Mobile UX", "Payments"],
    desc:
      "Built mobile food ordering experiences with responsive screens, API integrations, payment flows, and real-time delivery interactions. Worked with backend developers to connect mobile features to APIs, improve cross-platform compatibility, and support Agile delivery cycles.",
    logo: "FC",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/fudap_logo_zm6jb3.png",
    logoColor: "#2a2a1a",
    domain: "",
  },
  {
    role: "Frontend Developer",
    company: "Zummit Africa",
    location: "Remote",
    period: "Jul 2020 – Dec 2020",
    stack: ["React", "Next.js", "TypeScript", "MUI", "AWS", "Storybook"],
    desc:
      "Developed frontend interfaces for an AI learning and marketplace platform. Built responsive UI systems, improved cross-browser compatibility, contributed to reusable components, and helped document frontend patterns to support faster team delivery.",
    logo: "ZA",
    logoUrl: "https://zummitafrica.com/meta/apple-touch-icon.png",
    logoColor: "#1a2a2a",
    domain: "zummitafrica.com",
  },
  {
    role: "Junior Web Development Instructor",
    company: "Aptech Computer Institute",
    location: "Nigeria",
    period: "Apr 2020 – Aug 2021",
    stack: ["HTML", "CSS", "JavaScript", "React", "Mentorship"],
    desc:
      "Mentored early-stage developers in web development fundamentals, frontend engineering, and practical project delivery. Supported students through hands-on coding sessions, project guidance, debugging, and career development while strengthening my own leadership and communication skills.",
    logo: "AP",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/cropped-aptech-logo-180x180_hwb94c.jpg",
    logoColor: "#383E56",
    domain: "",
  },
  {
    role: "Freelance Software Developer",
    company: "Freelance / Client Projects",
    location: "Remote",
    period: "Mar 2019 – Present",
    stack: ["React", "Django", "Flutter", "SEO", "Performance", "Client Delivery"],
    desc:
      "Delivered websites, mobile apps, dashboards, and client-facing digital products across e-commerce, security, accessibility, music, wellness, and business services. Improved site performance, resolved critical bugs, optimised user experience, and handled end-to-end delivery from requirements to deployment.",
    logo: "FL",
    logoUrl: "https://res.cloudinary.com/dkrutkbjs/image/upload/v1777031534/Upwork-Logo-1_pum3kj.png",
    logoColor: "#111827",
    domain: "github.com/creedtech",
  },
];
// export const projects = [
//   {
//     num: "01",
//     title: "PAA - Property Analysis Assistant",
//     desc: "AI-powered property intelligence platform with mapping, yield calculations, comparables, and planning insights. Built data-heavy UI, map-based querying, and investor workflows.",
//     tags: ["Next.js", "TypeScript", "Maps", "AI", "Web3", "PostGIS"],
//     year: "2026",
//     href: "https://paa.scansanproperties.com",
//     featured: true,
//     company: "ScanSan Properties",
//     logo: "SS",
//     logoUrl:
//       "https://static.wixstatic.com/media/d1ac02_fb90f30d1cc445efbee8efb1e79bd24e%7Emv2.png",
//     logoColor: "#1a3a1a",
//   },
//   {
//     num: "02",
//     title: "ScanSan Browser Extension",
//     desc: "Property intelligence extension overlaying insights directly on listing platforms. Built lightweight high-performance UI, API integrations, and contextual data injection.",
//     tags: ["React", "TypeScript", "Browser Extension", "Performance"],
//     year: "2026",
//     href: "#",
//     featured: true,
//     company: "ScanSan Properties",
//     logo: "SE",
//     logoUrl: "",
//     logoColor: "#1a3a1a",
//   },
//   {
//     num: "03",
//     title: "RentSpace Full Platform Rebuild",
//     desc: "Rebuilt an entire PropTech + FinTech ecosystem (web, mobile, backend) in under a month. Introduced payments, rewards system, and scalable architecture.",
//     tags: ["Next.js", "Flutter", "Node.js", "MongoDB", "Paystack"],
//     year: "2025",
//     href: "https://rentspace.tech",
//     featured: true,
//     company: "RentSpace Technologies",
//     logo: "RT",
//     logoUrl: "https://rentspace.tech/img/logo/logo-light.png",
//     logoColor: "#1a1a3a",
//   },
//   {
//     num: "04",
//     title: "SwiftWave (Utility Payment System)",
//     desc: "Multi-service platform for airtime, bills, betting, and subscriptions. Designed architecture for scalable transactions and third-party integrations.",
//     tags: ["Node.js", "Payments", "APIs"],
//     year: "2025",
//     href: "#",
//     featured: true,
//     company: "Personal Project",
//     logo: "SW",
//     logoUrl: "",
//     logoColor: "#0f172a",
//   },
//   {
//     num: "05",
//     title: "Nigerian Food Delivery Platform (London)",
//     desc: "Full-stack ordering platform with delivery flows, payments, and real-time updates. Built for diaspora market.",
//     tags: ["React", "Node.js", "Payments", "UX"],
//     year: "2026",
//     href: "#",
//     featured: true,
//     company: "Personal Project",
//     logo: "FD",
//     logoUrl: "",
//     logoColor: "#7c2d12",
//   },
//   {
//     num: "06",
//     title: "Vanguard Media Platform",
//     desc: "High-scale news platform serving millions of users monthly. Improved engagement and ad revenue via frontend optimisation.",
//     tags: ["React", "Node.js", "Flutter", "Redis"],
//     year: "2023",
//     href: "https://vanguardngr.com",
//     featured: true,
//     company: "Vanguard Media",
//     logo: "VM",
//     logoUrl: "https://vanguardngr.com/wp-content/uploads/2022/08/logo.png",
//     logoColor: "#3a1a1a",
//   },
// ];

// export const experience = [
//   {
//     role: "Senior Frontend Engineer",
//     company: "ScanSan Properties",
//     location: "London, UK",
//     period: "June 2025 – Present",
//     stack: ["Next.js", "TypeScript", "Tailwind", "Maps", "Web3"],
//     desc:
//       "Leading frontend development for a Web3-powered property investment platform. Built the Property Analysis Assistant (PAA), delivering complex data visualisation tools including yield analysis, comparables, and geospatial insights. Contributed to white-labelling architecture, browser extension tooling, and performance optimisation across map-heavy interfaces.",
//     logo: "SS",
//     logoUrl:
//       "https://static.wixstatic.com/media/d1ac02_fb90f30d1cc445efbee8efb1e79bd24e%7Emv2.png",
//     logoColor: "#1a3a1a",
//     domain: "scansanproperties.com",
//   },
//   {
//     role: "Software Developer",
//     company: "RentSpace Technologies",
//     location: "London, UK",
//     period: "Aug 2023 – May 2025",
//     stack: ["Flutter", "Node.js", "MongoDB", "Paystack", "Flutterwave"],
//     desc:
//       "Rebuilt and scaled a PropTech + FinTech platform across web, mobile, and backend. Implemented payments, savings flows, and reward systems, supporting thousands of users. Led architectural decisions and contributed to hiring and onboarding engineers.",
//     logo: "RT",
//     logoUrl: "https://rentspace.tech/img/logo/logo-light.png",
//     logoColor: "#1a1a3a",
//     domain: "rentspace.tech",
//   },
//   {
//     role: "Senior Full-Stack Developer",
//     company: "Vanguard Media Limited",
//     location: "Remote",
//     period: "Apr 2022 – Aug 2023",
//     stack: ["React", "Node.js", "Flutter", "Redis"],
//     desc:
//       "Built and optimised high-traffic web and mobile applications serving millions of users. Improved performance and engagement through frontend and backend optimisations, contributing to significant growth in mobile ad revenue.",
//     logo: "VM",
//     logoUrl: "https://vanguardngr.com/wp-content/uploads/2022/08/logo.png",
//     logoColor: "#3a1a1a",
//     domain: "vanguardngr.com",
//   },
//   {
//     role: "Software Developer",
//     company: "Dowell Research UK",
//     location: "London, UK",
//     period: "Nov 2021 – Mar 2022",
//     stack: ["React", "Python", "AWS", "Stripe"],
//     desc:
//       "Developed a full-stack research platform for enterprise clients. Focused on scalable frontend architecture and integrated secure multi-currency payment systems.",
//     logo: "DR",
//     logoUrl:
//       "https://i0.wp.com/dowellresearch.uk/wp-content/uploads/2018/07/logo-e1531386713115.png",
//     logoColor: "#2a1a2a",
//     domain: "dowellresearch.uk",
//   },
//   {
//     role: "Frontend Mobile Developer",
//     company: "FUDAP CO",
//     location: "Remote",
//     period: "Jan 2021 – Oct 2021",
//     stack: ["React Native"],
//     desc:
//       "Built a mobile food delivery application with real-time tracking and in-app payments. Improved performance and user retention through optimised mobile experience.",
//     logo: "FC",
//     logoUrl: "",
//     logoColor: "#2a2a1a",
//     domain: "",
//   },
//   {
//     role: "Frontend Developer",
//     company: "Zummit Africa",
//     location: "Remote",
//     period: "Jul 2020 – Dec 2020",
//     stack: ["React", "Storybook", "Tailwind"],
//     desc:
//       "Developed UI systems for an AI learning platform. Improved performance through lazy loading and code splitting, and introduced component documentation with Storybook.",
//     logo: "ZA",
//     logoUrl: "https://zummitafrica.com/meta/apple-touch-icon.png",
//     logoColor: "#1a2a2a",
//     domain: "zummitafrica.com",
//   },
// ];
export const skills = [
  // Frontend
  "React",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "Tailwind CSS",
  "Redux Toolkit",

  // Mobile
  "Flutter",
  "React Native",

  // Backend
  "Node.js",
  "Express",
  "MongoDB",
  "PostgreSQL",

  // Systems
  "Redis",
  "Bull Queue",
  "REST APIs",
  "System Design",

  // Infra
  "AWS",
  "Firebase",
  "Docker",
  "Vercel",
  "Render",

  // Advanced
  "Web3",
  "Geospatial Systems",
  "Map-based Rendering",
  "Performance Optimisation",
  "Real-time Systems",
  "Payment Integrations",
];

export const socials = [
  { label: "GitHub", href: "https://github.com/creedtech", icon: "github" },
  { label: "LinkedIn", href: "https://linkedin.com/in/ayodele-ayoola", icon: "linkedin" },
  { label: "Twitter / X", href: "https://twitter.com/lazy_programma", icon: "twitter" },
];


export const GITHUB_USERNAME = "creedtech"; 
